"""delete 'created_date' index

Revision ID: 0fa998dcfe89
Revises: 1965eb8a4eef
Create Date: 2026-10-03 19:38:04.806920

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0fa998dcfe89"
down_revision: str | Sequence[str] | None = "1965eb8a4eef"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_documents_created_date"), table_name="documents")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_documents_created_date"), "documents", ["created_date"], unique=False)
    # ### end Alembic commands ###
